name: noisygiant
favicon: null
layout_spectrum: 0.9105
typography_spectrum: 0.41993
title: A Resourceful Noisy Giant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b6b8b9'
    - '#27262b'
    - '#fed3c1'
    - '#ae7f71'
    - '#7a5741'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
